name: Build contributors graph

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Generate Contributors Graph
        run: go run .
        env:
          TOKEN: ${{ github.token }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "contributors-graph"
          path: contributors.svg

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "contributors-graph"
